version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - "dbdata:/var/lib/mysql"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      DATABASE_URL: "mysql2://root:password@db:3306"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

volumes:
  dbdata:
